### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function children() on null

### ISSUE THREAD

**Issue by samsonasik** [kahlan/kahlan#176]
on unexistence namespace.
```
$ bin/kahlan --coverage="set\Set::normalize()"
            _     _
  /\ /\__ _| |__ | | __ _ _ __
 / //_/ _` | '_ \| |/ _` | '_ \
/ __ \ (_| | | | | | (_| | | | |
\/  \/\__,_|_| |_|_|\__,_|_| |_|

The PHP Test Framework for Freedom, Truth and Justice.

Working Directory: /Users/samsonasik/www/extra-matcher

............                                                      12 / 12 (100%)



Expectations   : 17 Executed
Specifications : 0 Pending, 0 Excluded, 0 Skipped

Passed 12 of 12 PASS in 0.087 seconds (using 2Mo)

Coverage Summary
----------------

Unexisting namespace: `set\Set::normalize()`, coverage can't be generated.

PHP Fatal error:  Uncaught Error: Call to a member function children() on null in /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Reporter/Coverage.php:173
Stack trace:
#0 /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Reporter/Coverage.php(370): Kahlan\Reporter\Coverage->_renderMetrics(NULL, 'set\\Set::normal...')
#1 /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Reporters.php(86): Kahlan\Reporter\Coverage->stop(Object(Kahlan\Summary))
#2 /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Scope.php(576): Kahlan\Reporters->dispatch('stop', Object(Kahlan\Summary))
#3 /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Suite.php(497): Kahlan\Scope->report('stop', Object(Kahlan\Summary), true)
#4 /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Cli/Kahlan.php(635): Kahlan\Suite->stop()
#5 [internal function]: Kahlan\Cli\Kahlan->Kahlan\Cli\{closure}(Object(Kahlan\Filter\Chain))
#6 /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Filter/Filter.php(2 in /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Reporter/Coverage.php on line 173

Fatal error: Uncaught Error: Call to a member function children() on null in /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Reporter/Coverage.php on line 173

Error: Call to a member function children() on null in /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Reporter/Coverage.php on line 173

Call Stack:
    0.0003     365144   1. {main}() /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/bin/kahlan:0
    0.0070    1084752   2. Kahlan\Cli\Kahlan->run() /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/bin/kahlan:47
    0.0073    1112472   3. Kahlan\Filter\Filter::on() /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Cli/Kahlan.php:370
    0.0076    1132160   4. call_user_func_array:{/Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Filter/Filter.php:213}() /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Filter/Filter.php:213
    0.0076    1132552   5. Kahlan\Cli\Kahlan->Kahlan\Cli\{closure}() /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Filter/Filter.php:213
    0.0943    2468720   6. Kahlan\Cli\Kahlan->_stop() /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Cli/Kahlan.php:367
    0.0943    2469096   7. Kahlan\Filter\Filter::on() /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Cli/Kahlan.php:636
    0.0944    2470480   8. call_user_func_array:{/Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Filter/Filter.php:213}() /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Filter/Filter.php:213
    0.0944    2470872   9. Kahlan\Cli\Kahlan->Kahlan\Cli\{closure}() /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Filter/Filter.php:213
    0.0944    2470872  10. Kahlan\Suite->stop() /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Cli/Kahlan.php:635
    0.0944    2470872  11. Kahlan\Scope->report() /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Suite.php:497
    0.0944    2470872  12. Kahlan\Reporters->dispatch() /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Scope.php:576
    0.0944    2470872  13. Kahlan\Reporter\Coverage->stop() /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Reporters.php:86
    0.1101    2681552  14. Kahlan\Reporter\Coverage->_renderMetrics() /Users/samsonasik/www/extra-matcher/vendor/kahlan/kahlan/src/Reporter/Coverage.php:370
```

**Comment by jails** [comment]
Yeah maybe we should display something less ugly on unexisting namespace

Le 16 oct. 2016 19:09, "Abdul Malik Ikhsan" <notifications@github.com> a
écrit :

**Comment by jails** [comment]
Fixed in https://github.com/kahlan/kahlan/commit/4366539e5321a7190d3c8029b660a9edd2ebcca7
