### ISSUE TITLE
Documentation code leads to `Call to undefined method Closure::next()`

### ISSUE THREAD

**Issue by yookoala** [kahlan/kahlan#290]
Version: kahlan 4.0.5

Just tried to inject variable to the global scope (as described [here](https://kahlan.github.io/docs/pro-tips.html)). I found that even a bare minimal kahlan-config.php would trigger error.

My config looks like this.

```php
<?php

use \Kahlan\Filter\Filters;

Filters::apply($this, 'run', function($chain) {
    return $chain->next();
});
```

I then run the following commands in the same folder:

```bash
composer require --dev kahlan/kahlan
mkdir spec
mkdir src
./vendor/bin/kahlan
```

The following errors appear
```
PHP Fatal error:  Uncaught Error: Call to undefined method Closure::next() in /foobar/project/kahlan-config.php:6
Stack trace:
#0 [internal function]: Kahlan\Cli\Kahlan->{closure}(Object(Closure))
#1 /foobar/project/vendor/kahlan/kahlan/src/Filter/Filters.php(204): call_user_func_array(Object(Closure), Array)
#2 [internal function]: Kahlan\Filter\Filters::Kahlan\Filter\{closure}()
#3 /foobar/project/vendor/kahlan/kahlan/src/Filter/Filters.php(206): call_user_func_array(Object(Closure), Array)
#4 /foobar/project/vendor/kahlan/kahlan/src/Cli/Kahlan.php(578): Kahlan\Filter\Filters::run(Object(Kahlan\Cli\Kahlan), 'run', Array, Object(Closure))
#5 /foobar/project/vendor/kahlan/kahlan/src/Cli/Kahlan.php(379): Kahlan\Cli\Kahlan->_run()
#6 [internal function]: Kahlan\Cli\Kahlan->Kahlan\Cli\{closure}(Object(Closure))
#7 /foobar/project/vendor/kahlan/kahlan/src/Filter/Filters.p in /foobar/project/kahlan-config.php on line 6
```

**Comment by samsonasik** [comment]
you should can use invokable `$chain` itself, like the following: 

```php 
<?php

use \Kahlan\Filter\Filters;

Filters::apply($this, 'run', function($chain) {
    return $chain();
});
```

The `$chain` itself is now a next itself.

**Comment by yookoala** [comment]
@samsonasik Thanks for the tip. It works.

Now that means the documentation website is outdated.
Every section is still suggesting to `return $chain->next();`.

**Comment by samsonasik** [comment]
fixed.

**Comment by jails** [comment]
Good catch !
