### ISSUE TITLE
kahlan 4.1 Too few arguments to function Kahlan\Plugin\Monkey::patched()

### ISSUE THREAD

**Issue by samsonasik** [kahlan/kahlan#297]
I tried kahlan 4.1.1 and now got the following errors:

```
kahlan:
   [kahlan]
   [kahlan] Fatal error: Uncaught ArgumentCountError: Too few arguments to function Kahlan\Plugin\Monkey::patched(), 2 passed in /private/var/folders/q6/4grzj1mj50g2fflkfl94yjp00000gp/T/kahlan/Users/samsonasik/www/app/vendor/paragonie/random_compat/lib/random.php on line 1 and at least 3 expected in /Users/samsonasik/www/app/vendor/kahlan/kahlan/src/Plugin/Monkey.php on line 52
   [kahlan]
   [kahlan] ArgumentCountError: Too few arguments to function Kahlan\Plugin\Monkey::patched(), 2 passed in /private/var/folders/q6/4grzj1mj50g2fflkfl94yjp00000gp/T/kahlan/Users/samsonasik/www/app/vendor/paragonie/random_compat/lib/random.php on line 1 and at least 3 expected in /Users/samsonasik/www/app/vendor/kahlan/kahlan/src/Plugin/Monkey.php on line 52
   [kahlan]
   [kahlan] Call Stack:
   [kahlan]     0.0004     410256   1. {main}() /Users/samsonasik/www/app/vendor/kahlan/kahlan/bin/kahlan:0
   [kahlan]     0.0112    1360960   2. Kahlan\Jit\ClassLoader->loadFile() /Users/samsonasik/www/app/vendor/kahlan/kahlan/bin/kahlan:57
   [kahlan]     0.0115    1387968   3. require('/private/var/folders/q6/4grzj1mj50g2fflkfl94yjp00000gp/T/kahlan/Users/samsonasik/www/app/vendor/paragonie/random_compat/lib/random.php') /Users/samsonasik/www/app/vendor/kahlan/kahlan/src/Jit/ClassLoader.php:251
   [kahlan]     0.0118    1403056   4. Kahlan\Plugin\Monkey::patched() /private/var/folders/q6/4grzj1mj50g2fflkfl94yjp00000gp/T/kahlan/Users/samsonasik/www/app/vendor/paragonie/random_compat/lib/random.php:1
   [kahlan]
   [kahlan] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Kahlan\Plugin\Monkey::patched(), 2 passed in /private/var/folders/q6/4grzj1mj50g2fflkfl94yjp00000gp/T/kahlan/Users/samsonasik/www/app/vendor/paragonie/random_compat/lib/random.php on line 1 and at least 3 expected in /Users/samsonasik/www/app/vendor/kahlan/kahlan/src/Plugin/Monkey.php:52
   [kahlan] Stack trace:
   [kahlan] #0 /private/var/folders/q6/4grzj1mj50g2fflkfl94yjp00000gp/T/kahlan/Users/samsonasik/www/app/vendor/paragonie/random_compat/lib/random.php(1): Kahlan\Plugin\Monkey::patched('', 'defined')
   [kahlan] #1 /Users/samsonasik/www/app/vendor/kahlan/kahlan/src/Jit/ClassLoader.php(251): require('/private/var/fo...')
   [kahlan] #2 /Users/samsonasik/www/app/vendor/kahlan/kahlan/bin/kahlan(57): Kahlan\Jit\ClassLoader->loadFile('/Users/samsonas...')
   [kahlan] #3 {main}
   [kahlan]   thrown in /Users/samsonasik/www/app/vendor/kahlan/kahlan/src/Plugin/Monkey.php on line 52

BUILD FAILED
/Users/samsonasik/www/app/build.xml:15: exec returned: 255
```

**Comment by samsonasik** [comment]
The issue seems when load a paragonie random compat library.

**Comment by jails** [comment]
Did you cleared up your cache directory ?

**Comment by samsonasik** [comment]
@jails Thank you, clear the cache fixed it.
