### ISSUE TITLE
Problem generating clover report

### ISSUE THREAD

**Issue by prolic** [kahlan/kahlan#346]
Steps to reproduce:
```
git clone git@github.com:prolic/fpp.git
composer install
php -dzend_extension=xdebug ./vendor/bin/kahlan --clover ./build/logs/clover.xml
```

**Comment by prolic** [comment]
Outputs:

```
PHP Fatal error:  Uncaught RuntimeException: Missing file name in /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Reporter/Coverage/Exporter/Clover.php:24
Stack trace:
#0 /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Cli/Kahlan.php(601): Kahlan\Reporter\Coverage\Exporter\Clover::write(Array)
#1 [internal function]: Kahlan\Cli\Kahlan->Kahlan\Cli\{closure}(Object(Closure))
#2 /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php(204): call_user_func_array(Object(Closure), Array)
#3 [internal function]: Kahlan\Filter\Filters::Kahlan\Filter\{closure}()
#4 /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php(206): call_user_func_array(Object(Closure), Array)
#5 /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Cli/Kahlan.php(616): Kahlan\Filter\Filters::run(Object(Kahlan\Cli\Kahlan), 'reporting', Array, Object(Closure))
#6 /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Cli/Kahlan.php(385): Kahlan\Cli\Kahlan->_reporting()
#7 [internal function]: Kahlan\Cli\Kahlan->Kahlan\Cli\{closure}(Object(Closure))
#8 /home/sasa/code/fp in /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Reporter/Coverage/Exporter/Clover.php on line 24

Fatal error: Uncaught RuntimeException: Missing file name in /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Reporter/Coverage/Exporter/Clover.php on line 24
```

**Comment by prolic** [comment]
Dumping that options array gives this:

```
/home/sasa/code/fpp/vendor/kahlan/kahlan/src/Reporter/Coverage/Exporter/Clover.php:24:
array(2) {
  'collector' =>
  class Kahlan\Reporter\Coverage#62 (18) {
    protected $_time =>
    int(0)
    protected $_verbosity =>
    int(1)
    protected $_collector =>
    class Kahlan\Reporter\Coverage\Collector#63 (11) {
      protected $_classes =>
      array(1) {
        ...
      }
      protected $_driver =>
      class Kahlan\Reporter\Coverage\Driver\Xdebug#61 (1) {
        ...
      }
      protected $_paths =>
      array(1) {
        ...
      }
      protected $_base =>
      string(19) "/home/sasa/code/fpp"
      protected $_prefix =>
      string(11) "/tmp/kahlan"
      protected $_hasVolume =>
      bool(false)
      protected $_files =>
      array(0) {
        ...
      }
      protected $_coverage =>
      array(10) {
        ...
      }
      protected $_metrics =>
      array(0) {
        ...
      }
      protected $_tree =>
      array(0) {
        ...
      }
      protected $_processed =>
      array(0) {
        ...
      }
    }
    protected $_enabled =>
    bool(true)
    protected $_prefixes =>
    array(0) {
    }
    protected $_newLine =>
    bool(true)
    protected $_indent =>
    int(0)
    protected $_indentValue =>
    string(2) "  "
    protected $_prefix =>
    string(0) ""
    protected $_header =>
    bool(true)
    protected $_colors =>
    bool(true)
    protected $_output =>
    resource(97) of type (stream)
    protected $_symbols =>
    array(3) {
      'ok' =>
      string(3) "✓"
      'err' =>
      string(3) "✖"
      'dot' =>
      string(1) "."
    }
    protected $_srcDir =>
    array(1) {
      [0] =>
      string(3) "src"
    }
    protected $_specDir =>
    array(1) {
      [0] =>
      string(4) "spec"
    }
    protected $_start =>
    double(1586716761.3315)
    protected $_total =>
    int(0)
    protected $_current =>
    int(52)
  }
  'file' =>
  NULL
}
```

**Comment by prolic** [comment]
@samsonasik any ideas?

**Comment by samsonasik** [comment]
@jails do you have a chance to check it ?

**Comment by jails** [comment]
I don't use Xdebug, but with `php7.4` & `php7.4-phpdbg` isntalled I ran the following with no issue:

```
git clone git@github.com:prolic/fpp.git
cd fpp
composer install
phpdbg -d memory_limit=256M -qrr ./vendor/bin/kahlan --reporter=verbose --clover=clover.xml
```

**Comment by prolic** [comment]
I just retried right now and the problem is gone. I don't know, maybe some caching issue. I'm closing this for now and will reopen again when the problem comes up again and I can provide some more information.

Thanks both @jails and @samsonasik .

**Comment by prolic** [comment]
Ok, this problem popped up again, I don't know what the difference is, see travis build here: https://travis-ci.org/github/prolic/fpp/jobs/678377545

**Comment by samsonasik** [comment]
probably cache, please try with `-cc` option

**Comment by prolic** [comment]
I tried that already.
Sascha-Oliver Prolic


Am Do., 23. Apr. 2020 um 01:36 Uhr schrieb Abdul Malik Ikhsan <
notifications@github.com>:

**Comment by jails** [comment]
Try to dynamically allocate more memory when running your specs like so:
```
php -d memory_limit=256M ./vendor/bin/kahlan --clover ./build/logs/clover.xml
```

**Comment by prolic** [comment]
I tried this right now:

```
php -dzend_extension=xdebug.so -dxdebug.max_nesting_level=1000 -dmemory_limit=512M ./vendor/bin/kahlan --coverage-text --clover ./build/logs/clover.xml --cc
            _     _
  /\ /\__ _| |__ | | __ _ _ __
 / //_/ _` | '_ \| |/ _` | '_ \
/ __ \ (_| | | | | | (_| | | | |
\/  \/\__,_|_| |_|_|\__,_|_| |_|

The PHP Test Framework for Freedom, Truth and Justice.

src directory  : /home/sasa/code/fpp/src
spec directory : /home/sasa/code/fpp/spec

................................................................. 65 / 71 ( 91%)
......                                                            71 / 71 (100%)



Expectations   : 108 Executed
Specifications : 0 Pending, 0 Excluded, 0 Skipped

Passed 71 of 71 PASS in 13.025 seconds (using 12MB)

PHP Fatal error:  Uncaught RuntimeException: Missing file name in /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Reporter/Coverage/Exporter/Clover.php:24
Stack trace:
#0 /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Cli/Kahlan.php(601): Kahlan\Reporter\Coverage\Exporter\Clover::write(Array)
#1 [internal function]: Kahlan\Cli\Kahlan->Kahlan\Cli\{closure}(Object(Closure))
#2 /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php(204): call_user_func_array(Object(Closure), Array)
#3 [internal function]: Kahlan\Filter\Filters::Kahlan\Filter\{closure}()
#4 /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php(206): call_user_func_array(Object(Closure), Array)
#5 /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Cli/Kahlan.php(616): Kahlan\Filter\Filters::run(Object(Kahlan\Cli\Kahlan), 'reporting', Array, Object(Closure))
#6 /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Cli/Kahlan.php(385): Kahlan\Cli\Kahlan->_reporting()
#7 [internal function]: Kahlan\Cli\Kahlan->Kahlan\Cli\{closure}(Object(Closure))
#8 /home/sasa/code/fp in /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Reporter/Coverage/Exporter/Clover.php on line 24

Fatal error: Uncaught RuntimeException: Missing file name in /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Reporter/Coverage/Exporter/Clover.php on line 24

RuntimeException: Missing file name in /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Reporter/Coverage/Exporter/Clover.php on line 24

Call Stack:
    0.0002     413056   1. {main}() /home/sasa/code/fpp/vendor/kahlan/kahlan/bin/kahlan:0
    0.0688    4151720   2. Kahlan\Cli\Kahlan->run() /home/sasa/code/fpp/vendor/kahlan/kahlan/bin/kahlan:69
    0.0688    4152040   3. Kahlan\Filter\Filters::run() /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Cli/Kahlan.php:390
    0.0689    4153720   4. call_user_func_array:{/home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php:206}() /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php:206
    0.0689    4153728   5. Kahlan\Filter\Filters::Kahlan\Filter\{closure:/home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php:199-205}() /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php:206
    0.0689    4153976   6. call_user_func_array:{/home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php:204}() /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php:204
    0.0689    4153992   7. Kahlan\Cli\Kahlan->Kahlan\Cli\{closure:/home/sasa/code/fpp/vendor/kahlan/kahlan/src/Cli/Kahlan.php:372-390}() /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php:204
   13.0935   10188288   8. Kahlan\Cli\Kahlan->_reporting() /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Cli/Kahlan.php:385
   13.0935   10188608   9. Kahlan\Filter\Filters::run() /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Cli/Kahlan.php:616
   13.0935   10190288  10. call_user_func_array:{/home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php:206}() /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php:206
   13.0935   10190296  11. Kahlan\Filter\Filters::Kahlan\Filter\{closure:/home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php:199-205}() /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php:206
   13.0935   10190544  12. call_user_func_array:{/home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php:204}() /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php:204
   13.0935   10190560  13. Kahlan\Cli\Kahlan->Kahlan\Cli\{closure:/home/sasa/code/fpp/vendor/kahlan/kahlan/src/Cli/Kahlan.php:593-616}() /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Filter/Filters.php:204
   13.0937   10208384  14. Kahlan\Reporter\Coverage\Exporter\Clover::write() /home/sasa/code/fpp/vendor/kahlan/kahlan/src/Cli/Kahlan.php:601

php -dzend_extension=xdebug.so -dxdebug.max_nesting_level=1000    --clover    13,05s user 0,01s system 99% cpu 13,109 total
```

**Comment by jails** [comment]
I think the option is `--clover=./build/logs/clover.xml`, not `--clover ./build/logs/clover.xml`

**Comment by prolic** [comment]
That's it! Working fine. The exception message could be better, though :)

Thanks a lot, you saved my day! Cheers!
