### ISSUE TITLE
Unable to run the tests when `XDEBUG_MODE` have multiple values

### ISSUE THREAD

**Issue by feryardiant** [kahlan/kahlan#386]
OS : Win 10 & Ubuntu WSL
PHP : 8.0.7
Xdebug : 3.0.3

When we have `xdebug.mode` set to multiple value, e.g. `coverage,debug,develop`, we'll see `RuntimeException`

```
$ bin/kahlan --config=kahlan-config.travis.php --clover=clover.xml
PHP Fatal error:  Uncaught RuntimeException: You need to set either `xdebug.mode=coverage` in your php.ini or the `XDEBUG_MODE=coverage` env variable. in /mnt/d/Workspace/Codes/kahlan/src/Reporter/Coverage/Driver/Xdebug.php:37
Stack trace:
#0 /mnt/d/Workspace/Codes/kahlan/kahlan-config.travis.php(19): Kahlan\Reporter\Coverage\Driver\Xdebug->__construct()
#1 [internal function]: Kahlan\Cli\Kahlan->{closure}()
#2 /mnt/d/Workspace/Codes/kahlan/src/Filter/Filters.php(204): call_user_func_array()
#3 [internal function]: Kahlan\Filter\Filters::Kahlan\Filter\{closure}()
#4 /mnt/d/Workspace/Codes/kahlan/src/Filter/Filters.php(206): call_user_func_array()
#5 /mnt/d/Workspace/Codes/kahlan/src/Cli/Kahlan.php(560): Kahlan\Filter\Filters::run()
#6 /mnt/d/Workspace/Codes/kahlan/src/Cli/Kahlan.php(466): Kahlan\Cli\Kahlan->_coverage()
#7 [internal function]: Kahlan\Cli\Kahlan->Kahlan\Cli\{closure}()
#8 /mnt/d/Workspace/Codes/kahlan/src/Filter/Filters.php(204): call_user_func_array()
#9 [internal function]: Kahlan\Filter\Filters::Kahlan\Filter\{closure}()
#10 /mnt/d/Workspace/Codes/kahlan/src/Filter/Filters.php(206): call_user_func_array()
#11 /mnt/d/Workspace/Codes/kahlan/src/Cli/Kahlan.php(467): Kahlan\Filter\Filters::run()
#12 /mnt/d/Workspace/Codes/kahlan/src/Cli/Kahlan.php(379): Kahlan\Cli\Kahlan->_reporters()
#13 [internal function]: Kahlan\Cli\Kahlan->Kahlan\Cli\{closure}()
#14 /mnt/d/Workspace/Codes/kahlan/src/Filter/Filters.php(204): call_user_func_array()
#15 [internal function]: Kahlan\Filter\Filters::Kahlan\Filter\{closure}()
#16 /mnt/d/Workspace/Codes/kahlan/src/Filter/Filters.php(206): call_user_func_array()
#17 /mnt/d/Workspace/Codes/kahlan/src/Cli/Kahlan.php(390): Kahlan\Filter\Filters::run()
#18 /mnt/d/Workspace/Codes/kahlan/bin/kahlan(71): Kahlan\Cli\Kahlan->run()
#19 {main}
  thrown in /mnt/d/Workspace/Codes/kahlan/src/Reporter/Coverage/Driver/Xdebug.php on line 37
```

PR coming 😁

**Comment by jails** [comment]
Thanks, fixed in https://github.com/kahlan/kahlan/commit/1a60fbc9dff8ddb239741caa1be9768f467d5bc3
